apiVersion: uyuni.uyuni-project.org/v1alpha1
kind: Server
metadata:
  labels:
    app.kubernetes.io/name: server
    app.kubernetes.io/instance: server-sample
    app.kubernetes.io/part-of: uyuni-server-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: uyuni-server-operator
  name: server-sample
spec:
  # TODO(user): Add fields here
